### ISSUE TITLE
[Evolution] "[p]evolution market store" errors when run in DMs

### ISSUE THREAD

**Issue by chloecormier** [NeuroAssassin/Toxic-Cogs#32]
Running the `[p]evolution market store` command causes an error when run in DMs, it works fine if the same person runs it in a server instead:
```
Exception in command 'evolution market store'
Traceback (most recent call last):
  File "/home/red/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/red/.local/share/Red-DiscordBot/cogs/CogManager/cogs/evolution/evolution.py", line 189, in store
    if ctx.channel.permissions_for(ctx.guild.me).embed_links:
AttributeError: 'NoneType' object has no attribute 'me'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/red/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/home/red/.local/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 825, in invoke
    await super().invoke(ctx)
  File "/home/red/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1307, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/red/.local/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 825, in invoke
    await super().invoke(ctx)
  File "/home/red/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1307, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/red/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/red/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'me'
```

**Comment by comitodedito** [comment]
@chloecormier [p]evolution u should have [p]suicidevolution instead u tf2c prancing male in wig

![ezgif-4-53ffca5be9](https://user-images.githubusercontent.com/107486488/173593550-49b0e0ac-2ffc-4ba1-8eeb-081255a99631.gif)
![re2](https://user-images.githubusercontent.com/107486488/173593553-a2a0acaf-8ac5-42ba-8e87-fed291977dfc.png)
