### ISSUE TITLE
[Dashboard] Start Error

### ISSUE THREAD

**Issue by DairyWeb3638077** [NeuroAssassin/Toxic-Cogs#74]
So I reinstalled the dashboard from scratch and when I got down to the part where you have to start the dashboard via `reddash`, I get this error...
```md
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Owner\reddashenv\Scripts\reddash.exe\__main__.py", line 4, in <module>
  File "C:\Users\Owner\reddashenv\lib\site-packages\reddash\__main__.py", line 7, in <module>
    from reddash.app import create_app
  File "C:\Users\Owner\reddashenv\lib\site-packages\reddash\app\__init__.py", line 8, in <module>
    from flask import Flask, url_for, session, render_template
  File "C:\Users\Owner\reddashenv\lib\site-packages\flask\__init__.py", line 19, in <module>
    from . import json
  File "C:\Users\Owner\reddashenv\lib\site-packages\flask\json\__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (C:\Users\Owner\reddashenv\lib\site-packages\itsdangerous\__init__.py)
```
I have no clue why I get this error as I have installed the dashboard from scratch.

**Comment by NeuroAssassin** [comment]
This error pertains to the webserver client of Red Dashboard.  This repository concerns only the cog connection for the Redbot.  Please move your issue to Cog-Creators/Red-Dashboard.
